[package]
name = "containerd-shim-wasm"
description = "Library for building containerd shims for wasm"
version = "0.2.0"
edition.workspace = true
license.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
containerd-shim = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
oci-spec = { workspace = true }
command-fds = "0.2"
serde = { workspace = true }
thiserror = { workspace = true }
protobuf = "3.2"
ttrpc = { workspace = true }
nix = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
clone3 = "0.2"
libc = { workspace = true }
caps = "0.5"
proc-mounts = "0.3"
libcontainer = { workspace = true, optional = true }

[build-dependencies]
ttrpc-codegen = { version = "0.4.2", optional = true }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1"
signal-hook = "0.3"
env_logger = { workspace = true }
rand = "0.8"

[features]
default = ["libcontainer", "libcontainer/default"]
libcontainer = ["dep:libcontainer"]
generate_bindings = ["ttrpc-codegen"]
generate_doc = []
libseccomp = ["libcontainer", "libcontainer/libseccomp"]
systemd = ["libcontainer", "libcontainer/systemd"]
v2 = ["libcontainer", "libcontainer/v2"]
v1 = ["libcontainer", "libcontainer/v1"]
cgroupsv2_devices = ["libcontainer", "libcontainer/cgroupsv2_devices"]