[workspace]
members = [
    "crates/containerd-shim-wasm",
    "crates/wasi-demo-app",
    "crates/oci-tar-builder",
    "crates/thirdparty",
    "crates/wasmedge",
    "crates/wasmtime",
]

[profile.release]
panic = "abort"
