[package]
name = "oci-tar-builder"
version.workspace = true
edition.workspace = true

[dependencies]
tar = { workspace = true }
sha256 = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
oci-spec =  { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }