name: Run end to end tests on kind

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      runtime:
        required: true
        type: string

jobs:
  e2e-kind:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: insightsengineering/disk-space-reclaimer@v1
        with:
          tools-cache: true
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          swap-storage: false
          docker-images: false
      - name: "check cgroup version"
        run: "mount | grep cgroup"
      - uses: actions/checkout@v3
      - name: setup rust-wasm target
        run: rustup target add wasm32-wasi
      - name: Setup build env
        run: ./scripts/setup-linux.sh
        shell: bash
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: containerd-shim-${{ inputs.runtime }}-${{ inputs.os }}
          path: dist
      - name: Unpack artifats
        shell: bash
        run: |
          mkdir -p dist/bin
          tar -xzf dist/containerd-shim-${{ inputs.runtime }}-${{ inputs.os }}.tar.gz -C dist/bin
      - name: run
        run: make test/k8s
      # only runs when the previous step fails
      - name: inspect failed pods
        if: failure()
        run: |
          kubectl get pods --all-namespaces
          kubectl describe pods --all-namespaces
      - name: cleanup
        if: always()
        run: make test/k8s/clean
