name: Build shims

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      runtime:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: insightsengineering/disk-space-reclaimer@v1
        if: runner.os == 'Linux'
        with:
          tools-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false
          docker-images: true
      - name: "check cgroup version"
        run: "mount | grep cgroup"
        if: runner.os == 'Linux'
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        env:
          RUST_CACHE_KEY_OS: ${{ inputs.os }}
        with:
          rustflags: '' #Disable.  By default this action sets environment variable is set to -D warnings.  We manage this in the Makefile
      - name: Setup build env
        run: |
          os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
          ./scripts/setup-$os.sh
        shell: bash
      - name: Set environment variables for Windows
        if: runner.os == 'Windows'
        run: |
          echo "WASMEDGE_LIB_DIR=C:\Program Files\WasmEdge\lib" >> $env:GITHUB_ENV
          echo "WASMEDGE_INCLUDE_DIR=C:\Program Files\WasmEdge\include" >> $env:GITHUB_ENV
      - name: Build
        run: make build RUNTIMES=${{ inputs.runtime }}
      - name: Validate docs
        run: ./scripts/validate-docs.sh
      - name: Run tests
        run: |
          make test
      - name: Package artifacts
        shell: bash
        run: |
          make dist RUNTIMES=${{ inputs.runtime }}
          # Check if there's any files to archive as tar fails otherwise
          if stat dist/bin/* >/dev/null 2>&1; then
            tar -czf dist/containerd-shim-${{ inputs.runtime }}-${{ inputs.os }}.tar.gz -C dist/bin .
          else
            tar -czf dist/containerd-shim-${{ inputs.runtime }}-${{ inputs.os }}.tar.gz -T /dev/null
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: containerd-shim-${{ inputs.runtime }}-${{ inputs.os }}
          path: dist/containerd-shim-${{ inputs.runtime }}-${{ inputs.os }}.tar.gz
