name: Run end to end tests on kind

on:
  workflow_call:

jobs:
  test-image:
    name: build test image
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: make dist/img.tar
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: test-image
          path: dist/img.tar
