name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: lint
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    uses: ./.github/workflows/action-fmt.yml
    with:
      os: ${{ matrix.os }}

  build-ubuntu:
    name: ${{ matrix.runtime }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        runtime: ["wasmtime", "wasmedge"]
    uses: ./.github/workflows/action-build.yml
    with:
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}

  build-windows:
    name: ${{ matrix.runtime }}
    strategy:
      matrix:
        os: ["windows-latest"]
        runtime: ["wasmtime", "wasmedge"]
    uses: ./.github/workflows/action-build.yml
    with:
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}

  e2e-wasmtime:
    name: ${{ matrix.runtime }}
    needs: [build-ubuntu]
    strategy:
      matrix:
        # 20.04 uses cgroupv1, 22.04 uses cgroupv2
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        runtime:  ["wasmtime"]
    uses: ./.github/workflows/action-test-kind.yml
    with:
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}

  e2e-k3s:
    name: ${{ matrix.runtime }}
    needs: [build-ubuntu]
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
        runtime: ["wasmedge"]
    uses: ./.github/workflows/action-test-k3s.yml
    with:
      os: ${{ matrix.os }}
      runtime: ${{ matrix.runtime }}
